<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6xuxWgo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6xuxWgo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6xuxWgo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6xuxWgo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6xuxWgo\App_KernelDevDebugContainer([
    'container.build_hash' => '6xuxWgo',
    'container.build_id' => '552ff1f9',
    'container.build_time' => 1597313763,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6xuxWgo');
