<?php

namespace Container6xuxWgo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWalletControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\WalletController' shared autowired service.
     *
     * @return \App\Controller\WalletController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/WalletController.php';
        include_once \dirname(__DIR__, 4).'/src/Utils/FilterArrayTrait.php';
        include_once \dirname(__DIR__, 4).'/src/Api/IbanFirstApi.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-client-contracts/HttpClientInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-client/HttpClient.php';

        $a = \Symfony\Component\HttpClient\HttpClient::create([], 6);
        $a->setLogger(($container->privates['logger'] ?? ($container->privates['logger'] = new \Symfony\Component\HttpKernel\Log\Logger())));

        return $container->services['App\\Controller\\WalletController'] = new \App\Controller\WalletController(new \App\Api\IbanFirstApi($container->getEnv('API_IBAN_FIRST_URL'), $container->getEnv('API_IBAN_FIRST_LOGIN'), $container->getEnv('API_IBAN_FIRST_PASS'), $a));
    }
}
